erDiagram
    CLIENTES {
        int DNI PK
        varchar Nombre
        varchar Apellido
        varchar Direccion
        int Telefono
    }
    VEHICULOS {
        varchar Patente PK
        varchar Modelo
        varchar Color
    }
    MECANICOS {
        int Legajo PK
        varchar Nombre
        varchar Apellido
        varchar Rol
        bool Estado
    }
    REPUESTOS {
        int Id PK
        varchar Nombre
        int Precio
        varchar Fabricante
    }
    REPARACIONES {
        int id_reparacion PK
        date Fecha_entrada
        time Hora_entrada
        varchar Patente
        varchar Legajo
    }
    FICHA_TECNICA {
        int id_ficha PK
        varchar Tipo
        varchar Descripcion
        date Fecha
        varchar Patente
        varchar DNI
        varchar Legajo
    }
    FACTURACION {
        int id_factura PK
        date Fecha
        int Monto
        varchar DNI
        varchar Patente
    }
    MECANICO_REPARACIONES {
        varchar Legajo
        int id_reparacion
    }

    CLIENTES ||--o{ VEHICULOS : "posee"
    VEHICULOS ||--o{ REPARACIONES : "tiene"
    MECANICOS ||--o{ MECANICO_REPARACIONES : "realiza"
    REPARACIONES ||--o{ MECANICO_REPARACIONES : "incluye"
    VEHICULOS ||--o{ FICHA_TECNICA : "tiene"
    CLIENTES ||--o{ FICHA_TECNICA : "tiene"
    MECANICOS ||--o{ FICHA_TECNICA : "tiene"
    CLIENTES ||--o{ FACTURACION : "recibe"
    VEHICULOS ||--o{ FACTURACION : "asociado a"